# ═══════════════════════════════════════════════════════════════════════════════════════════════════════
# JUST-IN-TIME NETWORK ACCESS COMPOSITE ACTION FOR POWER PLATFORM GOVERNANCE
# ═══════════════════════════════════════════════════════════════════════════════════════════════════════
# Zero-trust network access management for Azure Storage Accounts containing Terraform state files,
# implementing temporary firewall rule management for secure CI/CD operations.
#
# 🎯 WHY THIS EXISTS:
# - Implements zero-trust security model eliminating permanently opened firewall rules for state storage
# - Enables secure Terraform operations in network-restricted environments without compromising security
# - Reduces attack surface by providing time-bounded access only during active CI/CD operations
# - Supports compliance requirements for network-level access controls on infrastructure state
#
# 🔒 SECURITY DECISIONS:
# - Uses temporary IP-based access rules that are automatically cleaned up after workflow completion
# - Implements principle of least privilege by granting access only to specific runner IP addresses
# - Validates IP address formats to prevent injection attacks through malformed network parameters
# - Provides comprehensive audit logging for all network access grant and revoke operations
#
# ⚙️ OPERATIONAL CONTEXT:
# - Handles Azure firewall rule propagation delays (30-60 seconds) through configurable wait times
# - Supports both automatic IP detection via api.ipify.org and manual IP override for complex networks
# - Implements retry logic in underlying script to handle transient Azure API failures gracefully
# - Designed for integration with cleanup workflows using GitHub Actions 'always()' condition
#
# 📋 INTEGRATION REQUIREMENTS:
# - Depends on scripts/utils/jit-network-access.sh for Azure CLI operations and error handling
# - Requires Azure CLI authentication with Storage Account Contributor or Network Contributor permissions
# - Needs internet connectivity to api.ipify.org for automatic runner IP detection in most scenarios
# - Must be paired with corresponding 'remove' action in workflow cleanup to prevent security holes
# ═══════════════════════════════════════════════════════════════════════════════════════════════════════

name: 'JIT Network Access for Terraform Backend'
description: 'Provides secure Just-In-Time network access management for Terraform backend storage with zero-trust principles'

# === INPUT PARAMETERS ===
# These inputs control the Just-In-Time network access management behavior,
# supporting both automated and manual IP management scenarios.
inputs:
  action:
    description: 'Network access operation to perform on storage account firewall'
    required: true
    default: 'add'
    # Supported values: 'add', 'remove'
    # 'add': Grants temporary network access by adding runner IP to allowed list
    # 'remove': Revokes network access by removing runner IP from allowed list
    #
    # Workflow Pattern:
    # 1. Start of workflow: action: 'add' (enable access)
    # 2. End of workflow: action: 'remove' (cleanup access)
    #
    # Security Considerations:
    # - Always ensure 'remove' operations run even if workflow fails
    # - Use workflow job cleanup steps or GitHub Actions 'always()' condition
    # - Default 'add' maintains backward compatibility with existing workflows

  storage-account-name:
    description: 'Azure Storage Account name containing Terraform state files'
    required: true
    # Format: Must be valid Azure Storage Account name (3-24 characters, lowercase, numbers only)
    # Example: 'terraformstate001', 'myorgterraform'
    #
    # Validation: Action will fail if storage account doesn't exist or is inaccessible
    # Security: This account should have network restrictions enabled
    # Best Practice: Use dedicated storage accounts for Terraform state only
    #
    # Required Azure RBAC permissions on this storage account:
    # - Storage Account Contributor (full management)
    # - OR Network Contributor (firewall management) + Storage Blob Data Contributor (state access)

  resource-group-name:
    description: 'Azure Resource Group containing the target storage account'
    required: true
    # Format: Valid Azure Resource Group name
    # Example: 'rg-terraform-state', 'terraform-backend-rg'
    #
    # Validation: Must exist and be accessible with current Azure credentials
    # Scope: Used for proper Azure CLI command scoping and resource identification
    # Security: Service principal must have access to this resource group

  runner-ip:
    description: 'Manual IP address override for testing and special scenarios'
    required: false
    # Format: Valid IPv4 address (e.g., '192.168.1.100', '203.0.113.42')
    # Default behavior: When omitted, action auto-detects public IP using api.ipify.org
    #
    # Use Cases:
    # - Testing with specific IP addresses
    # - Debugging network access issues
    # - Working with proxy or NAT environments where auto-detection fails
    # - Corporate environments with complex network routing
    #
    # Security: Only use trusted IP addresses - this IP will get storage access
    # Validation: Action validates IPv4 format before processing

# === COMPOSITE ACTION EXECUTION ===
# This action implements a three-step process for secure network access management:
# 1. IP Detection/Validation, 2. Environment Setup, 3. Azure CLI Operations
runs:
  using: 'composite'
  steps:
    # === STEP 1: AUTOMATIC IP DETECTION ===
    # Auto-detects the GitHub runner's public IP address for firewall rule management
    # This step only runs when no manual IP override is provided in inputs
    - name: Auto-Detect Runner Public IP Address
      id: get-ip
      if: inputs.runner-ip == ''
      shell: bash
      run: |
        echo "::notice title=IP Detection::🌐 Auto-detecting runner public IP address..."

        # === IP DETECTION WITH ERROR HANDLING ===
        # Use ipify.org service with timeout and error handling
        # This service provides simple, reliable IPv4 detection
        if DETECTED_IP=$(curl --silent --connect-timeout 10 --max-time 30 https://api.ipify.org 2>/dev/null); then
          # Validate that we got a valid IPv4 address format
          if [[ $DETECTED_IP =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
            echo "RUNNER_IP=$DETECTED_IP" >> $GITHUB_ENV
            echo "::notice title=IP Detected::✅ Runner IP successfully detected: $DETECTED_IP"
          else
            echo "::error title=Invalid IP Format::❌ Detected IP '$DETECTED_IP' is not a valid IPv4 address"
            exit 1
          fi
        else
          echo "::error title=IP Detection Failed::❌ Failed to detect runner IP address"
          echo "::error::This may be due to network connectivity issues or ipify.org service unavailability"
          echo "::error::Consider using the 'runner-ip' input parameter to manually specify the IP address"
          exit 1
        fi

        echo "::debug::IP detection completed successfully"

    # === STEP 2: MANUAL IP VALIDATION ===
    # Validates and sets manually provided IP address when specified in inputs
    # This step only runs when a manual IP override is provided
    - name: Validate and Set Manual IP Address
      if: inputs.runner-ip != ''
      shell: bash
      run: |
        echo "::notice title=Manual IP::🎯 Using manually specified IP address..."

        # === INPUT VALIDATION ===
        # Validate the manually provided IP address format
        # This prevents invalid IPs from being used in Azure CLI commands
        PROVIDED_IP="${{ inputs.runner-ip }}"

        if [[ $PROVIDED_IP =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
          # Additional validation: Check each octet is within valid range (0-255)
          IFS='.' read -r -a octets <<< "$PROVIDED_IP"
          for octet in "${octets[@]}"; do
            if ((octet > 255)); then
              echo "::error title=Invalid IP Range::❌ IP address '$PROVIDED_IP' contains invalid octet: $octet"
              echo "::error::Each part of the IP address must be between 0 and 255"
              exit 1
            fi
          done

          echo "RUNNER_IP=$PROVIDED_IP" >> $GITHUB_ENV
          echo "::notice title=Manual IP Set::✅ Using provided runner IP: $PROVIDED_IP"
        else
          echo "::error title=Invalid IP Format::❌ Provided IP '$PROVIDED_IP' is not a valid IPv4 address"
          echo "::error::IP address must be in format: xxx.xxx.xxx.xxx (e.g., 192.168.1.100)"
          exit 1
        fi

        echo "::debug::Manual IP validation completed successfully"

    # === STEP 3: AZURE NETWORK ACCESS MANAGEMENT ===
    # Executes the core Just-In-Time network access logic using the specialized script
    # This step handles all Azure CLI interactions and implements the actual firewall management
    - name: Execute JIT Network Access Management
      shell: bash
      run: |
        echo "::notice title=JIT Access Management::🔐 Managing Just-In-Time network access..."

        # === ENVIRONMENT VARIABLE SETUP ===
        # Export all required variables for the underlying script to consume
        # This approach keeps sensitive information out of command-line arguments
        export STORAGE_ACCOUNT_NAME="${{ inputs.storage-account-name }}"
        export RESOURCE_GROUP_NAME="${{ inputs.resource-group-name }}"
        export RUNNER_IP="${{ env.RUNNER_IP }}"
        export JIT_ACTION="${{ inputs.action }}"

        # === OPERATION CONTEXT LOGGING ===
        # Provide comprehensive logging for audit trails and troubleshooting
        # This information is crucial for security audits and operational debugging
        echo "::notice title=Operation Context::📋 JIT network access configuration:"
        echo "::notice::• Action: ${{ inputs.action }}"
        echo "::notice::• Storage Account: $STORAGE_ACCOUNT_NAME"
        echo "::notice::• Resource Group: $RESOURCE_GROUP_NAME"
        echo "::notice::• Runner IP: ${{ env.RUNNER_IP }}"
        echo "::notice::• Timestamp: $(date -u +"%Y-%m-%dT%H:%M:%SZ")"

        # === SCRIPT EXISTENCE VALIDATION ===
        # Verify the required script exists before attempting execution
        # This provides a clear error message if the dependency is missing
        SCRIPT_PATH="${GITHUB_WORKSPACE}/scripts/utils/jit-network-access.sh"

        if [ ! -f "$SCRIPT_PATH" ]; then
          echo "::error title=Script Not Found::❌ JIT network access script not found at: $SCRIPT_PATH"
          echo "::error::Ensure the jit-network-access.sh script exists in scripts/utils/ directory"
          echo "::error::This script is required for Azure CLI operations and firewall management"
          exit 1
        fi

        # === SCRIPT PERMISSIONS VALIDATION ===
        # Ensure the script has execute permissions
        # This prevents cryptic "Permission denied" errors during execution
        if [ ! -x "$SCRIPT_PATH" ]; then
          echo "::warning title=Script Permissions::⚠️ Making script executable..."
          chmod +x "$SCRIPT_PATH"
        fi

        # === AZURE JIT NETWORK ACCESS EXECUTION ===
        # Manages Azure Storage Account firewall rules for temporary Terraform backend access
        # Uses dedicated script for Azure CLI operations with comprehensive error handling
        echo "::debug::Executing JIT network access script with action: ${{ inputs.action }}"

        if "$SCRIPT_PATH" "${{ inputs.action }}"; then
          echo "::notice title=JIT Access Success::✅ Network access management completed successfully"

          # Provide action-specific success messages for clarity
          if [ "${{ inputs.action }}" = "add" ]; then
            echo "::notice title=Access Granted::🔓 Temporary network access granted to runner IP"
            echo "::notice::Terraform operations can now access the storage account"
          else
            echo "::notice title=Access Revoked::🔒 Network access successfully revoked from runner IP"
            echo "::notice::Storage account firewall rules have been cleaned up"
          fi
        else
          # Script execution failed - provide detailed error context
          echo "::error title=JIT Access Failed::❌ Network access management failed"
          echo "::error::The jit-network-access.sh script returned a non-zero exit code"
          echo "::error::Check the script output above for specific error details"
          echo "::error::Common causes: Azure authentication, RBAC permissions, network connectivity"
          exit 1
        fi

        echo "::debug::JIT network access management completed"
