# Output Values for Power Platform Environment Group Pattern Configuration
#
# Template-driven pattern outputs following AVM anti-corruption layer pattern.
# Provides discrete computed attributes for integration with governance systems.
# Includes template metadata and environment mapping information.

# ============================================================================
# OUTPUT SCHEMA VERSION
# ============================================================================

output "output_schema_version" {
  description = "The version of the output schema for this template-driven pattern module."
  value       = "1.0.0"
}

# ============================================================================
# PRIMARY OUTPUTS - Environment Group and Template Information
# ============================================================================

output "environment_group_id" {
  description = <<DESCRIPTION
The unique identifier of the created Power Platform Environment Group.

This output provides the primary key for referencing the environment group
created by this template-driven pattern. Use this ID to:
- Configure additional governance policies targeting this group
- Reference the group in external configuration management systems
- Set up environment routing rules and rule sets
- Integrate with monitoring and compliance reporting systems

Format: GUID (e.g., 12345678-1234-1234-1234-123456789012)
DESCRIPTION
  value       = module.environment_group.environment_group_id
}

output "environment_group_name" {
  description = <<DESCRIPTION
The display name of the created environment group.

Generated from workspace name with " - Environment Group" suffix.
Useful for validation, reporting, and cross-reference with environment IDs.
DESCRIPTION
  value       = module.environment_group.environment_group_name
}

output "workspace_template" {
  description = <<DESCRIPTION
The workspace template used for this deployment.

Indicates which predefined template was used to create the environment
structure. Available templates: basic, simple, enterprise.
DESCRIPTION
  value       = var.workspace_template
}

output "workspace_name" {
  description = <<DESCRIPTION
The workspace name used as the base for environment naming.

This is the user-provided workspace name that gets combined with
template-defined suffixes to create individual environment names.
DESCRIPTION
  value       = var.name
}

# ============================================================================
# ENVIRONMENT OUTPUTS - Template-Generated Environment Information
# ============================================================================

output "environment_ids" {
  description = <<DESCRIPTION
Map of environment identifiers created by the template.

Provides unique identifiers for all environments created based on the
selected workspace template. Map keys correspond to template environment
indices, values are the Power Platform environment GUIDs.

Usage: Reference specific environments for additional configuration
DESCRIPTION
  value = {
    for idx, env_module in module.environments : idx => env_module.environment_id
  }
}

output "environment_names" {
  description = <<DESCRIPTION
Map of environment display names generated by the template.

Shows the actual environment names created by combining the workspace
name with template-defined suffixes (e.g., " - Dev", " - Test", " - Prod").
DESCRIPTION
  value = {
    for idx, env in local.environment_summary : idx => env.display_name
  }
}

output "environment_types" {
  description = <<DESCRIPTION
Map of environment types as defined by the template.

Shows the environment types (Sandbox, Production, Trial) for each
environment as specified in the workspace template configuration.
DESCRIPTION
  value = {
    for idx, env in local.environment_summary : idx => env.environment_type
  }
}

output "environment_suffixes" {
  description = <<DESCRIPTION
Map of environment name suffixes used by the template.

Shows the suffixes (e.g., " - Dev", " - Test", " - Prod") that were
applied to the workspace name to generate environment names.
DESCRIPTION
  value = {
    for idx, env in local.environment_summary : idx => env.suffix
  }
}

# ============================================================================
# STATE TRACKING OUTPUTS - For State-Aware Duplicate Detection
# ============================================================================

output "managed_environments" {
  description = <<DESCRIPTION
Tracking information for environments managed by this Terraform configuration.

This output enables state-aware duplicate detection by providing a lookup map
of all environments currently managed by this configuration. Used by the
duplicate detection logic to distinguish between:
- Environments that exist in platform but are managed by Terraform (allowed updates)
- Environments that exist in platform but are NOT managed (blocked duplicates)

Format: Map of lowercase display names to environment details
DESCRIPTION
  value = {
    for key, env_config in local.template_environments :
    lower(env_config.environment.display_name) => {
      id           = try(module.environments[key].environment_id, null)
      display_name = env_config.environment.display_name
      template_key = key
      scenario     = try(local.environment_scenarios[key].scenario, "unknown")
    }
    if try(module.environments[key].environment_id, null) != null
  }
}

output "environment_scenarios" {
  description = <<DESCRIPTION
Duplicate detection scenario analysis for each environment.

Provides transparency into the three-scenario decision logic:
- create_new: Environment doesn't exist in platform
- managed_update: Environment exists in platform AND in Terraform state  
- duplicate_blocked: Environment exists in platform but NOT in Terraform state

This output helps with debugging duplicate detection issues and understanding
why certain environments were or were not created.
DESCRIPTION
  value       = local.environment_scenarios
}

output "terraform_state_tracking" {
  description = <<DESCRIPTION
Terraform state tracking information for managed environments.

This output provides the actual terraform_data resource tracking information
that enables true state-aware duplicate detection. Each managed environment
has a corresponding terraform_data resource that persists in state.

This is the definitive source of truth for which environments are managed
by this Terraform configuration, eliminating circular dependency issues.
DESCRIPTION
  value = {
    for key, tracker in terraform_data.managed_environment_tracker : key => {
      environment_id = tracker.input.environment_id
      display_name   = tracker.input.display_name
      template_key   = tracker.input.template_key
      managed_by     = tracker.input.managed_by
      creation_time  = tracker.input.creation_time
      state_tracked  = true
    }
  }
}

# ============================================================================
# DEBUG OUTPUT - Enhanced debug for verifying duplicate detection fix
# ============================================================================

output "debug_state_lookup" {
  description = "Debug information to verify the new Terraform-compliant duplicate detection is working correctly"
  value = {
    # New Terraform-compliant approach debug
    naming_pattern_detection   = true
    expected_environment_names = local.expected_environment_names
    managed_envs_from_naming   = local.managed_envs_from_naming_pattern

    # Final comparison keys
    existing_state_managed_envs = local.existing_state_managed_envs
    platform_envs_keys          = keys(local.platform_envs)
    state_envs_keys             = keys(local.existing_state_managed_envs)

    # Scenario analysis
    environment_scenarios_debug = {
      for key, scenario in local.environment_scenarios : key => {
        target_name            = local.template_environments[key].environment.display_name
        target_name_lower      = lower(local.template_environments[key].environment.display_name)
        exists_in_platform     = scenario.exists_in_platform
        exists_in_state        = scenario.exists_in_state
        scenario               = scenario.scenario
        should_create_resource = scenario.should_create_resource

        # New debugging lookup details
        platform_lookup_key    = lower(local.template_environments[key].environment.display_name)
        state_lookup_key       = lower(local.template_environments[key].environment.display_name)
        found_in_platform      = contains(keys(local.platform_envs), lower(local.template_environments[key].environment.display_name))
        found_in_state         = contains(keys(local.existing_state_managed_envs), lower(local.template_environments[key].environment.display_name))
        matches_naming_pattern = contains(local.expected_environment_names, lower(local.template_environments[key].environment.display_name))
      }
    }
  }
}

# ============================================================================
# ADDITIONAL DEBUG OUTPUT - Duplicate Detection Investigation  
# ============================================================================

output "debug_duplicate_detection" {
  description = "Debug output to investigate why managed environments aren't being detected in state"
  value       = local.debug_state_detection
}

# ============================================================================
# ORCHESTRATION SUMMARY - Deployment Status and Validation
# ============================================================================

output "orchestration_summary" {
  description = "Summary of template-driven pattern deployment status and results"
  value = {
    # Deployment status
    deployment_status      = "deployed"
    pattern_complete       = local.deployment_validation.pattern_complete
    all_environments_ready = local.deployment_validation.all_environments_created
    group_assignment_valid = local.deployment_validation.group_assignment_valid

    # Resource metrics
    total_resources_created    = 1 + local.pattern_metadata.environment_count
    environment_group_id       = module.environment_group.environment_group_id
    environments_created       = local.pattern_metadata.environment_count
    managed_environments_count = local.pattern_metadata.environment_count

    # Template processing results
    template_processing = {
      template_loaded        = true
      location_validated     = local.deployment_validation.location_valid
      environments_generated = length(local.template_environments)
      naming_convention      = "workspace_name + template_suffix"
    }

    # Environment details from template
    environment_summary = local.environment_results

    # Integration readiness
    ready_for_governance = true
    ready_for_policies   = true
    ready_for_routing    = true

    # Timestamps
    deployment_timestamp = timestamp()
  }
}
