# Output Values for Power Platform Environment Group Pattern Configuration
#
# Template-driven pattern outputs following AVM anti-corruption layer pattern.
# Provides discrete computed attributes for integration with governance systems.
# Includes template metadata and environment mapping information.

# ============================================================================
# OUTPUT SCHEMA VERSION
# ============================================================================

locals {
  output_schema_version = "1.0.0"
}

output "output_schema_version" {
  description = "The version of the output schema for this template-driven pattern module."
  value       = local.output_schema_version
}

# ============================================================================
# PRIMARY OUTPUTS - Environment Group and Template Information
# ============================================================================

output "environment_group_id" {
  description = <<DESCRIPTION
The unique identifier of the created Power Platform Environment Group.

This output provides the primary key for referencing the environment group
created by this template-driven pattern. Use this ID to:
- Configure additional governance policies targeting this group
- Reference the group in external configuration management systems
- Set up environment routing rules and rule sets
- Integrate with monitoring and compliance reporting systems

Format: GUID (e.g., 12345678-1234-1234-1234-123456789012)
DESCRIPTION
  value       = module.environment_group.environment_group_id
}

output "environment_group_name" {
  description = <<DESCRIPTION
The display name of the created environment group.

Generated from workspace name with " - Environment Group" suffix.
Useful for validation, reporting, and cross-reference with environment IDs.
DESCRIPTION
  value       = module.environment_group.environment_group_name
}

output "workspace_template" {
  description = <<DESCRIPTION
The workspace template used for this deployment.

Indicates which predefined template was used to create the environment
structure. Available templates: basic, simple, enterprise.
DESCRIPTION
  value       = var.workspace_template
}

output "workspace_name" {
  description = <<DESCRIPTION
The workspace name used as the base for environment naming.

This is the user-provided workspace name that gets combined with
template-defined suffixes to create individual environment names.
DESCRIPTION
  value       = var.name
}

# ============================================================================
# ENVIRONMENT OUTPUTS - Template-Generated Environment Information
# ============================================================================

output "environment_ids" {
  description = <<DESCRIPTION
Map of environment identifiers created by the template.

Provides unique identifiers for all environments created based on the
selected workspace template. Map keys correspond to template environment
indices, values are the Power Platform environment GUIDs.

Usage: Reference specific environments for additional configuration
DESCRIPTION
  value = {
    for idx, env_module in module.environments : idx => env_module.environment_id
  }
}

output "environment_names" {
  description = <<DESCRIPTION
Map of environment display names generated by the template.

Shows the actual environment names created by combining the workspace
name with template-defined suffixes (e.g., " - Dev", " - Test", " - Prod").
DESCRIPTION
  value = {
    for idx, env in local.environment_summary : idx => env.display_name
  }
}

output "environment_types" {
  description = <<DESCRIPTION
Map of environment types as defined by the template.

Shows the environment types (Sandbox, Production, Trial) for each
environment as specified in the workspace template configuration.
DESCRIPTION
  value = {
    for idx, env in local.environment_summary : idx => env.environment_type
  }
}

output "environment_suffixes" {
  description = <<DESCRIPTION
Map of environment name suffixes used by the template.

Shows the suffixes (e.g., " - Dev", " - Test", " - Prod") that were
applied to the workspace name to generate environment names.
DESCRIPTION
  value = {
    for idx, env in local.environment_summary : idx => env.suffix
  }
}

# ============================================================================
# TEMPLATE METADATA - Template Configuration and Validation Summary
# ============================================================================

output "template_metadata" {
  description = "Metadata about the workspace template and its configuration"
  value = {
    # Template information
    template_name        = var.workspace_template
    template_description = local.pattern_metadata.template_description
    environment_count    = local.pattern_metadata.environment_count

    # Template validation
    template_valid = local.deployment_validation.template_valid
    location_valid = local.deployment_validation.location_valid

    # Workspace configuration
    workspace_name     = var.name
    workspace_desc     = var.description
    workspace_location = var.location

    # Pattern metadata
    pattern_type    = local.pattern_metadata.pattern_type
    pattern_version = local.output_schema_version
  }
}

# ============================================================================
# ORCHESTRATION SUMMARY - Deployment Status and Validation
# ============================================================================

output "orchestration_summary" {
  description = "Summary of template-driven pattern deployment status and results"
  value = {
    # Deployment status
    deployment_status      = "deployed"
    pattern_complete       = local.deployment_validation.pattern_complete
    all_environments_ready = local.deployment_validation.all_environments_created
    group_assignment_valid = local.deployment_validation.group_assignment_valid

    # Resource metrics
    total_resources_created = 1 + local.pattern_metadata.environment_count # Group + environments
    environment_group_id    = module.environment_group.environment_group_id
    environments_created    = local.pattern_metadata.environment_count

    # Template processing results
    template_processing = {
      template_loaded        = true
      location_validated     = local.deployment_validation.location_valid
      environments_generated = length(local.template_environments)
      naming_convention      = "workspace_name + template_suffix"
    }

    # Environment details from template
    environment_summary = local.environment_results

    # Integration readiness
    ready_for_governance = true
    ready_for_policies   = true
    ready_for_routing    = true

    # Timestamps
    deployment_timestamp = timestamp()
  }
}

# ============================================================================
# GOVERNANCE INTEGRATION - Resources Ready for Policy Application
# ============================================================================

output "governance_ready_resources" {
  description = "Map of resources ready for governance configuration and policy application"
  value = {
    environment_group = {
      id               = module.environment_group.environment_group_id
      name             = module.environment_group.environment_group_name
      resource_type    = "powerplatform_environment_group"
      governance_ready = true
      policy_targets   = ["dlp_policies", "routing_rules", "environment_rules"]
      template_driven  = true
      workspace_name   = var.name
    }

    environments = {
      for idx, env_module in module.environments : idx => {
        id                 = env_module.environment_id
        name               = local.environment_summary[idx].display_name
        resource_type      = "powerplatform_environment"
        environment_type   = local.environment_summary[idx].environment_type
        group_membership   = module.environment_group.environment_group_id
        governance_ready   = true
        policy_inheritance = "from_group"
        template_suffix    = local.environment_summary[idx].suffix
        workspace_name     = var.name
      }
    }
  }
}

# ============================================================================
# CONFIGURATION SUMMARY - Audit and Compliance Reporting
# ============================================================================

output "pattern_configuration_summary" {
  description = "Comprehensive summary of template-driven pattern configuration"
  value = {
    # Input configuration summary
    workspace_config = {
      template    = var.workspace_template
      name        = var.name
      description = var.description
      location    = var.location
      name_length = length(var.name)
      desc_length = length(var.description)
    }

    # Template processing summary
    template_processing = {
      template_name        = var.workspace_template
      template_description = local.pattern_metadata.template_description
      environments_defined = length(local.selected_template.environments)
      location_validation  = local.deployment_validation.location_valid
      allowed_locations    = local.selected_template.allowed_locations
    }

    # Environment generation summary
    environment_generation = {
      count             = local.pattern_metadata.environment_count
      naming_pattern    = "${var.name} + template_suffix"
      environment_types = [for env in local.environment_summary : env.environment_type]
      generated_names   = [for env in local.environment_summary : env.display_name]
      unique_names      = length(distinct([for env in local.environment_summary : env.display_name])) == length(local.environment_summary)
      dataverse_enabled = true
    }

    # Pattern orchestration summary
    orchestration_results = {
      pattern_executed      = true
      template_driven       = true
      resources_deployed    = 1 + local.pattern_metadata.environment_count
      dependency_order      = ["template_processing", "environment_group", "environments"]
      group_assignment_mode = "automatic"
      validation_passed     = local.deployment_validation.pattern_complete
    }

    # Compliance and audit information
    compliance_info = {
      avm_inspired          = true
      template_driven       = true
      security_model        = "oidc_only"
      provider_version      = "~> 3.8"
      anti_corruption_layer = true
      monitoring_sp_enabled = true
    }
  }
}