---
name: "🔄 Update GitHub Workflow"
description: Request an update to an existing GitHub Actions workflow following repository automation standards
title: "[GITHUB WORKFLOW] Update request: "
labels: ["automation", "workflow-update"]
projects: []
assignees: []
body:
  - type: textarea
    id: implementation_instructions
    attributes:
      label: Implementation Instructions (Auto-populated)
      description: "Required standards and processes that must be followed during workflow update"
      value: |
        ## 🚦 GitHub Workflow Update Request

        This form creates a task to update an existing workflow in `.github/workflows/` in accordance with repository automation and governance standards.

        ### 📋 Required Instructions:
        - **Baseline Standards**: Follow [baseline.instructions.md](/.github/instructions/baseline.instructions.md)
        - **Automation Standards**: Follow [github-automation.instructions.md](/.github/instructions/github-automation.instructions.md)
        - **YAML Formatting**: All updates must comply with project `.yamllint` configuration and pass all workflow validation checks

        ### ⚠️ Important Constraints:
        - **File Scope Restriction**: Only modify files within `.github/workflows/` and update `CHANGELOG.md` in the root
        - **Prohibited Modifications**: Do NOT modify LICENSE, README.md, docs/, scripts/, configurations/, or any action directory unless explicitly required for workflow integration
        - **Temporary Files**: Do NOT commit temporary files (*.tar.gz, *.zip, cache files)
        - **Validation Requirements**: All changes must pass YAML linting (`yamllint`), GitHub Actions validation (`actionlint`), and any compliance checks before completion
      render: markdown
    validations:
      required: false

  - type: input
    id: workflow_file_name
    attributes:
      label: Workflow File Name
      description: Exact name of the workflow file to update (e.g., `terraform-deploy.yml`)
      placeholder: "terraform-deploy.yml"
    validations:
      required: true

  - type: textarea
    id: primary_purpose
    attributes:
      label: Primary Purpose of Update
      description: Brief description of the intended change and the problem or opportunity it addresses
      placeholder: "Improve Azure authentication security by switching to OIDC and updating workflow permissions to principle of least privilege."
    validations:
      required: true

  - type: dropdown
    id: update_type
    attributes:
      label: Update Type
      description: Select the category that best describes this workflow update
      options:
        - "Security Enhancement (OIDC, secrets, permissions)"
        - "Governance/Compliance (environments, policy enforcement)"
        - "Reliability Improvement (timeouts, retries, error handling)"
        - "Performance Optimization (caching, matrix, conditional execution)"
        - "Documentation/Comments (add/update WHY comments, improve clarity)"
        - "Other"
    validations:
      required: true

  - type: textarea
    id: implementation_details
    attributes:
      label: Implementation Details
      description: Summarize specific jobs, steps, permissions, or YAML changes to be made. Include code snippets or YAML fragments if possible.
      placeholder: |
        - Switch Azure login to OIDC
        - Add step for validating configuration directory
        - Update permissions block to only include required scopes
        - Example YAML:
          permissions:
            contents: read
            id-token: write
            pull-requests: write
    validations:
      required: true

  - type: textarea
    id: reference_materials
    attributes:
      label: Reference Materials and Documentation
      description: |
        Provide links to official documentation, standards, related issues/PRs, or other reference materials that Copilot should use for context and implementation guidance.
      placeholder: |
        - GitHub Actions documentation for OIDC authentication
        - Existing workflow example in repository
        - Repository automation standards
    validations:
      required: true

  - type: textarea
    id: success_criteria
    attributes:
      label: Success Criteria (Auto-populated)
      description: "Validation requirements that serve as success criteria for this workflow update"
      value: |
        ## ✅ Success Criteria for GitHub Workflow Update

        **The following validation requirements serve as success criteria for this task:**

        ### 🔒 Security and Compliance
        - [ ] Explicit permissions set in workflow (`permissions:` block)
        - [ ] OIDC authentication for Azure and cloud provider connections (where applicable)
        - [ ] No hardcoded secrets or sensitive values in workflow

        ### ⚙️ Reliability and Modularity
        - [ ] Timeout and retry logic implemented for critical steps
        - [ ] Workflow size within repository limits (≤ 300 lines for individual workflows)
        - [ ] Jobs, steps, and inputs documented with clear WHY comments

        ### 📝 Documentation & Structure
        - [ ] Header with purpose, governance, security, and integration context (see [github-automation.instructions.md](/.github/instructions/github-automation.instructions.md))
        - [ ] Inline comments for non-obvious decisions, security, and governance context
        - [ ] CHANGELOG.md entry for workflow update

        ### 🛡️ Validation & Testing
        - [ ] Passes YAML linting (`yamllint`)
        - [ ] Passes GitHub Actions workflow validation (`actionlint`)
        - [ ] Passes compliance check with `validate-github-actions-compliance.sh`
      render: markdown
    validations:
      required: false
