# Smart DLP tfvars Generator: Data Processing Logic
#
# This file implements the core logic for generating tfvars files from exported DLP policy and connector data.
# Follows AVM and project standards: clear separation of concerns, security-first, and anti-corruption outputs.

# Load exported DLP policy and connector data (from JSON files generated by export utilities).
locals {
  dlp_policies_json = fileexists("${path.module}/terraform-output-utl-export-dlp-policies.json") ? file("${path.module}/terraform-output-utl-export-dlp-policies.json") : null
  connectors_json   = fileexists("${path.module}/terraform-output-utl-export-connectors.json") ? file("${path.module}/terraform-output-utl-export-connectors.json") : null
  dlp_policies      = local.dlp_policies_json != null ? jsondecode(local.dlp_policies_json) : {}
  connectors        = local.connectors_json != null ? jsondecode(local.connectors_json) : {}
}

# Determine operational mode: onboarding (from export) or template (new policy)
locals {
  onboarding_mode = var.source_policy_name != ""
  selected_policy = local.onboarding_mode && contains(keys(local.dlp_policies), var.source_policy_name) ? local.dlp_policies[var.source_policy_name] : null
  policy_name     = local.onboarding_mode ? var.source_policy_name : (var.policy_name != null ? var.policy_name : "New DLP Policy")
  template_type   = var.template_type != "" ? var.template_type : "strict-security"
}

# Classify connectors for tfvars output (business, non-business, blocked)
locals {
  business_connectors     = local.onboarding_mode && local.selected_policy != null ? local.selected_policy["business_connectors"] : []
  non_business_connectors = local.onboarding_mode && local.selected_policy != null ? local.selected_policy["non_business_connectors"] : []
  blocked_connectors      = local.onboarding_mode && local.selected_policy != null ? local.selected_policy["blocked_connectors"] : []
}

# Render tfvars content using the selected governance template
locals {
  tfvars_content = templatefile("${path.module}/templates/${local.template_type}.tftpl", {
    policy_name             = local.policy_name
    business_connectors     = local.business_connectors
    non_business_connectors = local.non_business_connectors
    blocked_connectors      = local.blocked_connectors
  })
}

# Validate that generated tfvars is not empty (basic completeness check)
locals {
  tfvars_valid = length(local.business_connectors) + length(local.non_business_connectors) + length(local.blocked_connectors) > 0
}

# Outputs are defined in outputs.tf (see anti-corruption layer pattern)
